### ISSUE TITLE
Review- Design Docs

### ISSUE THREAD

**Issue by jmeyer90** [gonsaje/Conterest#1]
MVP
- The description for your app which is currently in your MVP section should be in the Home section of your app.
- All MVPs must have a timeline.
- You may want to wait to have a user show page until your Dims are created.
- Please use full sentences and proper grammar when writing you Wiki. Recruiters will be reading this.

Schema
- Include all associations and indexing in you schema for each respective table.

Sample State
- We need to have other slices of our state present: ui, errors, and session.

Routes
- Complete all backend and frontend routes

**Comment by gonsaje** [comment]
Hey Justin,
Could you take a look at my Design Docs and let me know if there is anything that still needs to be touched up. Thank you!
